language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/target
before_cache:
  - find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - libtool
    - gcc-4.8
before_script:
  - export PATH="$PATH:$HOME/.cache/bin:$HOME/.cargo/bin"
  - GRPC_HEADER="$HOME/.cache/include/grpc/grpc.h"
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CC=gcc-4.8; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]] && [[ ! -f $GRPC_HEADER ]]; then export CC=clang; brew install autoconf automake libtool shtool; fi
  - test -f "$GRPC_HEADER" || (git clone -b v1.2.5 https://github.com/grpc/grpc && cd grpc && git submodule update --init && env prefix=$HOME/.cache make install_c)
  - export C_INCLUDE_PATH="$HOME/.cache/include"
  - export LD_LIBRARY_PATH="$HOME/.cache/lib"
  - export DYLD_LIBRARY_PATH="$HOME/.cache/lib"
  - export LIBRARY_PATH="$HOME/.cache/lib"
  - export PKG_CONFIG_PATH="$HOME/.cache/lib/pkgconfig"
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]] && [[ $TRAVIS_OS_NAME == "linux" ]]; then which rustfmt || cargo install rustfmt; fi
script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]] && [[ $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt -- --write-mode=diff; fi
  - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then FEATURES="dev"; else FEATURES="default"; fi
  - cargo build
  - cargo test --all --features "$FEATURES"
