branches:  
  only:
    - master

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - git submodule -q update --init --recursive
  - choco install yasm
  - choco install protoc
  - rustc -V
  - cargo -V
    
build: false

test_script:
  - SET RUSTFLAGS=-Dwarnings
  - cargo build
  - cargo test --all
