[package]
name = "grpc"
version = "0.1.0"

[dependencies]
grpc-sys = { path = "grpc-sys", version = "0.1" }
libc = "0.2"
futures = "0.1"
protobuf = "1.2"
clippy = { version = "*", optional = true }

[features]
default = []
dev = ["clippy"]
