[package]
name = "grpc"
version = "0.1.0"

[dependencies]
grpc-sys = { path = "grpc-sys", version = "0.1" }
libc = "0.2"
futures = "0.1"
protobuf = { version = "1.2", optional = true }
clippy = { version = "*", optional = true }

[workspace]
members = ["proto", "compiler"]

[features]
default = ["protobuf-codec"]
dev = ["clippy"]
protobuf-codec = ["protobuf"]
static-link = ["grpc-sys/static-link"]
