[package]
name = "grpc"
version = "0.1.0"

[dependencies]
grpc-sys = { path = "grpc-sys", version = "0.1" }
libc = "0.2"
futures = "0.1"
protobuf = { version = "1.2", optional = true }
clippy = { version = "*", optional = true }

[workspace]
members = ["proto", "compiler", "interop"]

[features]
default = ["protobuf-codec"]
dev = ["clippy"]
protobuf-codec = ["protobuf"]
static-link = ["grpc-sys/static-link"]

[[example]]
name = "route_guide_client"
path = "examples/route_guide/client.rs"

[[example]]
name = "route_guide_server"
path = "examples/route_guide/server.rs"

[[example]]
name = "greeter_client"
path = "examples/hello_world/client.rs"

[[example]]
name = "greeter_server"
path = "examples/hello_world/server.rs"

[dev-dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
grpc-proto = { path = "proto" }
rand = "0.3"

[profile.release]
debug = true
