[package]
name = "grpcio-compiler"
version = "0.2.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["compiler", "grpc", "protobuf"]
repository = "https://github.com/pingcap/grpc-rs"
homepage = "https://github.com/pingcap/grpc-rs"
documentation = "https://docs.rs/grpcio-compiler"
description = "gRPC compiler for grpcio"
categories = ["network-programming"]

[dependencies]
protobuf = ">=1.2, <1.6"

[[bin]]
name = "grpc_rust_plugin"
