[package]
name = "grpcio-compiler"
version = "0.5.0"
edition = "2018"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["compiler", "grpc", "protobuf"]
repository = "https://github.com/pingcap/grpc-rs"
homepage = "https://github.com/pingcap/grpc-rs"
documentation = "https://docs.rs/grpcio-compiler"
description = "gRPC compiler for grpcio"
categories = ["network-programming"]

[dependencies]
protobuf = "2.0"
protobuf-codegen = "2.0"
prost-build = { path = "../../prost/prost-build", version = "0.4.0" }
derive-new = "0.5"

[[bin]]
name = "grpc_rust_plugin"
